/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.sp.senac.projetointegradorII;

/**
 *
 * @author vinic
 */
public class TelaInicial2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial2
     */
    public TelaInicial2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harpa = new javax.swing.JLabel();
        microfone = new javax.swing.JLabel();
        teclado = new javax.swing.JLabel();
        flauta = new javax.swing.JLabel();
        bateria = new javax.swing.JLabel();
        baixo = new javax.swing.JLabel();
        violão = new javax.swing.JLabel();
        sanfona = new javax.swing.JLabel();
        pandeiro = new javax.swing.JLabel();
        violino = new javax.swing.JLabel();
        trompete = new javax.swing.JLabel();
        saxofone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        ImnuCliente = new javax.swing.JMenuItem();
        ImnuProduto = new javax.swing.JMenuItem();
        mnuVenda = new javax.swing.JMenu();
        ImnuRealizarVenda = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        ImnuSintetico = new javax.swing.JMenuItem();
        ImnuAnalitico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        setMinimumSize(new java.awt.Dimension(500, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        harpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/harpa.png"))); // NOI18N

        microfone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfone-com-fio.png"))); // NOI18N

        teclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teclado.png"))); // NOI18N

        flauta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flauta.png"))); // NOI18N

        bateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bateria.png"))); // NOI18N

        baixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baixo.png"))); // NOI18N

        violão.setIcon(new javax.swing.ImageIcon(getClass().getResource("/violao.png"))); // NOI18N

        sanfona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acordeao.png"))); // NOI18N

        pandeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumento-de-percussao-pandeiro.png"))); // NOI18N

        violino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/violino.png"))); // NOI18N

        trompete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trompete.png"))); // NOI18N

        saxofone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saxofone.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notas-musicais (1).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g-clef-nota-musical.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notas-musicais.png"))); // NOI18N

        mnuCadastro.setText("Cadastro");

        ImnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente3.png"))); // NOI18N
        ImnuCliente.setText("Cliente");
        ImnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImnuClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(ImnuCliente);

        ImnuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produto2.png"))); // NOI18N
        ImnuProduto.setText("Produto");
        ImnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImnuProdutoActionPerformed(evt);
            }
        });
        mnuCadastro.add(ImnuProduto);

        mnuPrincipal.add(mnuCadastro);

        mnuVenda.setText("Venda");

        ImnuRealizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venda2.png"))); // NOI18N
        ImnuRealizarVenda.setText("Realizar Venda");
        ImnuRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImnuRealizarVendaActionPerformed(evt);
            }
        });
        mnuVenda.add(ImnuRealizarVenda);

        mnuPrincipal.add(mnuVenda);

        mnuRelatorios.setText("Relatórios");

        ImnuSintetico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sintetico.png"))); // NOI18N
        ImnuSintetico.setText("Sintético");
        mnuRelatorios.add(ImnuSintetico);

        ImnuAnalitico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analitico.png"))); // NOI18N
        ImnuAnalitico.setText("Analítico");
        mnuRelatorios.add(ImnuAnalitico);

        mnuPrincipal.add(mnuRelatorios);

        jMenu1.setText("Opções");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair (2).png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mnuPrincipal.add(jMenu1);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(microfone))
                    .addComponent(teclado))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(harpa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(flauta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pandeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(violão, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(violino, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sanfona, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(bateria)
                .addGap(76, 76, 76)
                .addComponent(baixo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(trompete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(saxofone))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(microfone)
                        .addGap(86, 86, 86)
                        .addComponent(teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(harpa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(flauta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pandeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(violão, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(violino, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(sanfona, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bateria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(baixo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trompete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(saxofone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImnuClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImnuClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void ImnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImnuProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImnuProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ImnuRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImnuRealizarVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda venda = new TelaVenda();
        venda.setVisible(true);
    }//GEN-LAST:event_ImnuRealizarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ImnuAnalitico;
    private javax.swing.JMenuItem ImnuCliente;
    private javax.swing.JMenuItem ImnuProduto;
    private javax.swing.JMenuItem ImnuRealizarVenda;
    private javax.swing.JMenuItem ImnuSintetico;
    private javax.swing.JLabel baixo;
    private javax.swing.JLabel bateria;
    private javax.swing.JLabel flauta;
    private javax.swing.JLabel harpa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel microfone;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuVenda;
    private javax.swing.JLabel pandeiro;
    private javax.swing.JLabel sanfona;
    private javax.swing.JLabel saxofone;
    private javax.swing.JLabel teclado;
    private javax.swing.JLabel trompete;
    private javax.swing.JLabel violino;
    private javax.swing.JLabel violão;
    // End of variables declaration//GEN-END:variables
}
