/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.sp.senac.projetointegradorII.views;

import edu.sp.senac.projetointegradorII.DAO.TelaClienteDAO;
import edu.sp.senac.projetointegradorII.DAO.TelaProdutoDAO;
import edu.sp.senac.projetointegradorII.DAO.TelaVendaDAO;
import edu.sp.senac.projetointegradorII.model.Cliente;
import edu.sp.senac.projetointegradorII.model.Produto;
import edu.sp.senac.projetointegradorII.model.Venda;
import edu.sp.senac.projetointegradorII.validadores.Validador;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinic
 */
public class TelaVenda extends javax.swing.JFrame {
    
     int valorTotal = 0;
     int qtdeTotal = 0;

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        //Mudar ícone das telas
        ImageIcon img = new ImageIcon("src/main/resources/icons/musica.png");
        this.setIconImage(img.getImage());
        
        Calendar date = Calendar.getInstance();
        jdcDataVenda.setDate(date.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        lblNVenda = new javax.swing.JLabel();
        txtVenda = new javax.swing.JTextField();
        lblDataVenda = new javax.swing.JLabel();
        jdcDataVenda = new com.toedter.calendar.JDateChooser();
        lblBuscarCliente = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JFormattedTextField();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblVendedor = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JComboBox<>();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblDescricaoProduto = new javax.swing.JLabel();
        txtDescricaoProduto = new javax.swing.JTextField();
        lblQtde = new javax.swing.JLabel();
        txtQtde = new javax.swing.JSpinner();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        lblEstoque = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        btnInterir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        pnlDireita = new javax.swing.JPanel();
        lblCarrinho = new javax.swing.JLabel();
        txtCarrinho = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal1 = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlEsquerda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Venda");
        setMinimumSize(new java.awt.Dimension(700, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlSuperior.setBackground(new java.awt.Color(251, 250, 248));
        pnlSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNVenda.setText("Nº Venda");

        txtVenda.setEditable(false);
        txtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendaActionPerformed(evt);
            }
        });

        lblDataVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDataVenda.setText("Data Venda");

        lblBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBuscarCliente.setText("Buscar Cliente - CPF");

        try {
            txtBuscarCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarClienteFocusLost(evt);
            }
        });
        txtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeCliente.setText("Nome Cliente");

        txtNomeCliente.setEditable(false);

        lblVendedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVendedor.setText("Vendedor");

        txtVendedor.setBackground(new java.awt.Color(234, 215, 206));
        txtVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Vinicius Garcia", "Mateus Felipe", "Vinicius Lima", "Matheus Lima", "William Queiroz", "Miguel Palacio" }));

        lblProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProduto.setText("Produto");

        txtProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdutoFocusLost(evt);
            }
        });

        lblDescricaoProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescricaoProduto.setText("Nome Produto");

        txtDescricaoProduto.setEditable(false);
        txtDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoProdutoActionPerformed(evt);
            }
        });

        lblQtde.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtde.setText("Qtde.");

        lblValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValor.setText("Valor");

        txtValor.setEditable(false);
        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        lblEstoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstoque.setText("Estoque");

        txtEstoque.setEditable(false);

        btnInterir.setBackground(new java.awt.Color(234, 215, 206));
        btnInterir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInterir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionar-ao-carrinho.png"))); // NOI18N
        btnInterir.setText("Inserir");
        btnInterir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterirActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(234, 215, 206));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNVenda)
                            .addComponent(txtVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente)))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                        .addComponent(lblProduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricaoProduto)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQtde))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataVenda)
                                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jdcDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBuscarCliente)
                                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)))
                        .addGap(8, 8, 8)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstoque)
                            .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVendedor))))
                .addGap(18, 18, 18)
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInterir)
                    .addComponent(btnExcluir))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNVenda)
                                    .addComponent(lblNomeCliente))
                                .addGap(3, 3, 3)
                                .addComponent(txtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addComponent(lblBuscarCliente)
                                .addGap(37, 37, 37))
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtBuscarCliente))
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addComponent(lblDataVenda)
                                .addGap(3, 3, 3)
                                .addComponent(jdcDataVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInterir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProduto)
                            .addComponent(lblDescricaoProduto)
                            .addComponent(lblQtde)
                            .addComponent(lblValor))
                        .addGap(10, 10, 10)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricaoProduto)
                            .addComponent(txtProduto)
                            .addComponent(txtValor)
                            .addComponent(txtQtde)))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblEstoque))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVendedor)))
                        .addGap(7, 7, 7)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVendedor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEstoque))))))
                .addGap(11, 11, 11))
        );

        pnlDireita.setBackground(new java.awt.Color(251, 250, 248));
        pnlDireita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarrinho.setBackground(new java.awt.Color(251, 250, 248));
        lblCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCarrinho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carrinho-carrinho.png"))); // NOI18N
        lblCarrinho.setText("Carrinho");

        txtCarrinho.setEditable(false);
        txtCarrinho.setToolTipText("");
        txtCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarrinhoActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receive-amount.png"))); // NOI18N
        lblTotal.setText("Total");

        txtTotal1.setEditable(false);
        txtTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotal1ActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(234, 215, 206));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carrinho.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(234, 215, 206));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(234, 215, 206));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/casa.png"))); // NOI18N
        jButton1.setText("Início");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDireitaLayout = new javax.swing.GroupLayout(pnlDireita);
        pnlDireita.setLayout(pnlDireitaLayout);
        pnlDireitaLayout.setHorizontalGroup(
            pnlDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDireitaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addComponent(txtCarrinho)
                    .addComponent(lblCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotal1)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDireitaLayout.setVerticalGroup(
            pnlDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarrinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEsquerda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Qtde.", "Valor Unitário"
            }
        ));
        jScrollPane1.setViewportView(tbVenda);

        javax.swing.GroupLayout pnlEsquerdaLayout = new javax.swing.GroupLayout(pnlEsquerda);
        pnlEsquerda.setLayout(pnlEsquerdaLayout);
        pnlEsquerdaLayout.setHorizontalGroup(
            pnlEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEsquerdaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEsquerdaLayout.setVerticalGroup(
            pnlEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDireita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDireita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        
        Validador validador = new Validador();
        validador.ValidarVazioJDC(jdcDataVenda);
        validador.ValidarVazioJ(txtBuscarCliente);
        validador.ValidarVazio(txtNomeCliente);
        validador.ValidarVazioJCB(txtVendedor);
        validador.mensagem();
        
        ArrayList<Produto> listaItens = new ArrayList<Produto>();
        if(tbVenda.getRowCount() > 0){
                for(int i=0;i<tbVenda.getRowCount();i++){
                    Produto item = new Produto();

                    item.setCodigoProduto(Integer.parseInt(tbVenda.getValueAt(i, 0).toString()));
                    item.setNomeProduto(tbVenda.getValueAt(i, 1).toString());
                    item.setQuantProd(Integer.parseInt(tbVenda.getValueAt(i, 2).toString()));
                    item.setValorProduto(Double.parseDouble(tbVenda.getValueAt(i, 3).toString()));
                    
                    listaItens.add(item);
                }
        }
        
        txtTotal1.setText(String.valueOf(valorTotal));
        txtCarrinho.setText(Integer.toString(qtdeTotal));        
        
        Double valor = Double.parseDouble(txtTotal1.getText());
        Date DataVenda = jdcDataVenda.getDate();
        String cpfVenda = txtBuscarCliente.getText();
        String nomeCliente = txtNomeCliente.getText();
        String nomeProduto = txtDescricaoProduto.getText();
        
        Venda objVenda = new Venda();
        objVenda.setTotal(valor);
        objVenda.setListaItens(listaItens);
        objVenda.setDataVenda(DataVenda);
        objVenda.setBuscarCliente(cpfVenda);
        objVenda.setNomeCliente(nomeCliente);
        
        Produto objProduto = new Produto();
        objProduto.setNomeProduto(nomeProduto);

        boolean retorno = TelaVendaDAO.salvar(objVenda);
        if (retorno){
            AtualizaEstoque();
            limparTextoGeral();
            JOptionPane.showMessageDialog(this, "Venda feita com sucesso!");
            valorTotal = 0;
            qtdeTotal = 0;        
            
        } else{
            JOptionPane.showMessageDialog(this, "Falha na gravação!");
        }        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void AtualizaEstoque() {
        
        int estoqueSaida;
        int cod_produto;
        
        for (int i = 0; i < tbVenda.getRowCount(); i++) {
            cod_produto = Validador.objectToInt(tbVenda.getValueAt(i, 0));
            estoqueSaida = Validador.objectToInt(tbVenda.getValueAt(i, 2));
            
            Produto objProduto = new Produto();
            objProduto.setCodigoProduto(cod_produto);
            objProduto.setQuantProd(estoqueSaida);
            TelaProdutoDAO.atualizarEstoque(objProduto);
        }
    }
    
    private void txtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Compra Cancelada!");
        valorTotal = 0;
        qtdeTotal = 0; 
        limparTextoGeral();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInterirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterirActionPerformed
        // TODO add your handling code here:
        
        Validador validador = new Validador();
        validador.ValidarVazio(txtProduto);
        validador.ValidarVazio(txtDescricaoProduto);
        validador.ValidarVazioJS(txtQtde);
        validador.ValidarVazioJ(txtValor);
        validador.ValidarVazio(txtEstoque);
        validador.mensagem();
        
        
        int cod_produto = Integer.parseInt(txtProduto.getText());
        String descricao = txtDescricaoProduto.getText();
        int qtd = Integer.parseInt(txtQtde.getValue().toString());
        double valor = Double.parseDouble(txtValor.getText());
        
        int quantidade = Integer.parseInt(txtQtde.getValue().toString());
        int estoque = Integer.parseInt(txtEstoque.getText());
        
        
        if (quantidade <= estoque && quantidade != 0) {
            
            DefaultTableModel modelo = (DefaultTableModel) tbVenda.getModel();
            modelo.addRow(new String[]{
                                    String.valueOf(cod_produto),
                                    descricao, 
                                    String.valueOf(qtd),
                                    String.valueOf(valor)
                                    }
                    );
        
        double valorLinha = qtd * valor;
        valorTotal += valorLinha;
        
        int valorLinhaQtd = qtd;
        qtdeTotal += valorLinhaQtd;
        
        txtTotal1.setText(String.valueOf(valorTotal));
        txtCarrinho.setText(Integer.toString(qtdeTotal));
        
        limparTexto();
        
        } else {
            JOptionPane.showMessageDialog(null, "Erro na compra, escolha uma quantidade menor ao disponível em estoque e diferente de Zero");
        }
    }//GEN-LAST:event_btnInterirActionPerformed

    private void txtProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdutoFocusLost
        // TODO add your handling code here:
        if(!txtProduto.getText().trim().equals("")){
            int id = Integer.parseInt(txtProduto.getText());
            Produto prod = TelaProdutoDAO.consultarPorID(id);

            if (prod != null) {
                txtDescricaoProduto.setText(prod.getNomeProduto());
                txtValor.setText(String.valueOf(prod.getValorProduto()));
                txtEstoque.setText(String.valueOf(prod.getQuantProd()));
                
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
            }
        }
    }//GEN-LAST:event_txtProdutoFocusLost

    private void txtTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal1ActionPerformed

    private void txtDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoProdutoActionPerformed

    private void txtBuscarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarClienteFocusLost
        // TODO add your handling code here:

        if(!txtBuscarCliente.getText().trim().equals("")){
            String id = txtBuscarCliente.getText();
            Cliente prod = TelaClienteDAO.consultarPorCPF(id);

            if (prod != null) {
                txtNomeCliente.setText(prod.getNome()); 
            } else {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
                limparTextoGeral();
            }
        }
    }//GEN-LAST:event_txtBuscarClienteFocusLost

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tbVenda.getSelectedRow();
        
        int qtdTb = Integer.parseInt(tbVenda.getValueAt(linha, 2).toString());
        double valorTb = Double.parseDouble(tbVenda.getValueAt(linha, 3).toString());
        
        int qtd = Integer.parseInt(txtCarrinho.getText());
        double valor = Integer.parseInt(txtTotal1.getText());
        
        int valorLinha = (int) (qtdTb * valorTb);
        valorTotal = (int) (valor - valorLinha);
        
        qtdeTotal = qtd - qtdTb;
        
        txtTotal1.setText(String.valueOf(valorTotal));
        txtCarrinho.setText(Integer.toString(qtdeTotal));
        
        DefaultTableModel modelo = (DefaultTableModel) tbVenda.getModel();
        modelo.removeRow(linha); 
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarClienteActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarrinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }
    
    private void limparTexto() {
        
        txtProduto.setText("");
        txtDescricaoProduto.setText("");
        txtQtde.setValue(0);
        txtValor.setText("");
        txtEstoque.setText("");
               
    }
    
    private void limparTextoGeral() {
            
        jdcDataVenda.setDate(null);
        txtBuscarCliente.setText("");
        txtVendedor.setSelectedItem("Selecione...");
        txtEstoque.setText("");        
        txtProduto.setText("");
        txtQtde.setValue(0);
        txtValor.setText("");
        txtNomeCliente.setText("");
        txtDescricaoProduto.setText("");
        txtCarrinho.setText("");
        txtTotal1.setText(""); 
        
        DefaultTableModel modelo = (DefaultTableModel) tbVenda.getModel();
        modelo.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnInterir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcDataVenda;
    private javax.swing.JLabel lblBuscarCliente;
    private javax.swing.JLabel lblCarrinho;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblNVenda;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtde;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel pnlDireita;
    private javax.swing.JPanel pnlEsquerda;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTable tbVenda;
    private javax.swing.JFormattedTextField txtBuscarCliente;
    private javax.swing.JTextField txtCarrinho;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JSpinner txtQtde;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JTextField txtVenda;
    private javax.swing.JComboBox<String> txtVendedor;
    // End of variables declaration//GEN-END:variables
}
